config/routes.rb
Mayushee::Application.routes.draw do
  devise_for :users

  root :to => 'projects#index'

  resources :projects, shallow: true do
    resources :duties
    resources :sprints
    resources :stories do
      resources :tasks
    end
  end

  resources :users
end

app/models/duty.rb
class Duty < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  belongs_to :role
end

app/controllers/duties_controller.rb
class DutiesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :set_project

  authorize_resource

  def index
    @duties = @project.duties.includes(:user, :role)
  end

  def new
    @users = User.all
    @roles = Role.all
    @duty = Duty.new
  end

  def create
    if @project.duties.create(duty_params)
      redirect_to project_duties_url(@project)
    else
      render :new
    end
  end

  private

    def set_project
      @project = Project.find(params[:project_id])
    end

    def duty_params
      params.require(:duty).permit(:role_id, :user_id)
    end
end

app/helpers/duties_helper.rb
module DutiesHelper
end

app/views/duties/index.html.erb
<div class="row-fluid">
  <div class="span2">
    <%= render 'shared/sidebar' %>
  </div>
  <div class="span10">
    <h1><%= @project.name %></h1>
    <p><%= link_to 'Add User', new_project_duty_path(@project), class: 'btn pull-right' %></p>

    <table class='table'>
      <tr>
        <th>User</th>
        <th>Role</th>
        <th></th>
      </tr>
      <% @duties.each do |duty| %>
        <tr>
          <td><%= duty.user.name %></td>
          <td><%= duty.role.name_text %></td>
          <td></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/duties/new.html.erb
<h1>New duty</h1>

<%= form_for([@project, @duty], html: { class: 'form-horizontal' }) do |f| %>
  <% if @duty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@duty.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% @duty.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :user, class: 'control-label' %>
    <div class="controls">
      <%= f.collection_select :user_id, @users, :id, :name %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :role, class: 'control-label' %>
    <div class="controls">
      <%= f.collection_select :role_id, @roles, :id, :name_text %>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <%= f.submit "Create", class: 'btn' %>
    </div>
  </div>
<% end %>