config/routes.rb
Mayushee::Application.routes.draw do
  devise_for :users

  root :to => 'projects#index'

  resources :projects, shallow: true do
    resources :duties
    resources :sprints
    resources :stories do
      resources :tasks
    end
  end

  resources :users
end

app/models/user.rb
class User < ActiveRecord::Base
  extend Enumerize
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :commitments
  has_many :duties
  has_many :projects, through: :duties
  has_many :roles, through: :duties
  has_many :work_hours

  validates :login, presence: true, length: { maximum: 20 }
  validates :role, presence: true

  enumerize :role, in: %w[admin develop test]
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  authorize_resource

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_url, notice: 'user was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to users_url, notice: 'user was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:login, :password, :password_confirmation, :name, :email, :role)
    end
end

app/views/users/edit.html.erb
<h2>Edit User</h2>

<%= form_for(@user, html: { class: 'form-horizontal' }) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :login, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :login, placeholder: 'Login', autofocus: true %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password, class: 'control-label' %>
    <div class="controls">
      <%= f.password_field :password, placeholder: 'Password' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password_confirmation, class: 'control-label' %>
    <div class="controls">
      <%= f.password_field :password_confirmation, placeholder: 'Password confirmation' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :name, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, placeholder: 'Name' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, class: 'control-label' %>
    <div class="controls">
      <%= f.email_field :email, placeholder: 'Email' %>
    </div>
  </div>
  <% unless @user == current_user %>
    <div class="control-group">
      <%= f.label :role, class: 'control-label' %>
      <div class="controls">
        <%= f.select :role, User.role.options %>
      </div>
    </div>
  <% end %>
  <div class="control-group">
    <div class="controls">
      <%= f.submit "Update", class: 'btn' %>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="row-fluid">
  <div class="span12">
    <h1>Listing Users</h1>
    <table class="table">
      <tr>
        <th></th>
        <th>Name</th>
        <th>Email</th>
        <th></th>
      </tr>

      <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.id, user %></td>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= link_to 'Edit', edit_user_path(user), class: 'btn btn-success' %></td>
        </tr>
      <% end %>
    </table>

    <br />

    <%= link_to 'New user', new_user_path, class: 'btn btn-primary' %>
  </div>
</div>

app/views/users/new.html.erb
<h2>Create User</h2>

<%= form_for(@user, html: { class: 'form-horizontal' }) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :login, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :login, placeholder: 'Login', autofocus: true %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password, class: 'control-label' %>
    <div class="controls">
      <%= f.password_field :password, placeholder: 'Password' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password_confirmation, class: 'control-label' %>
    <div class="controls">
      <%= f.password_field :password_confirmation, placeholder: 'Password confirmation' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :name, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, placeholder: 'Name' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, class: 'control-label' %>
    <div class="controls">
      <%= f.email_field :email, placeholder: 'Email' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :role, class: 'control-label' %>
    <div class="controls">
      <%= f.select :role, User.role.options %>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <%= f.submit "Create", class: 'btn' %>
    </div>
  </div>
<% end %>