config/routes.rb
Mayushee::Application.routes.draw do
  devise_for :users

  root :to => 'projects#index'

  resources :projects, shallow: true do
    resources :duties
    resources :sprints
    resources :stories do
      resources :tasks
    end
  end

  resources :users
end

app/models/story.rb
class Story < ActiveRecord::Base
  has_many :tasks, dependent: :destroy
  has_many :plannings, dependent: :destroy
  belongs_to :project

  def hours_left
    self.tasks.empty? ? 0 : self.tasks.map(&:hours_left).sum
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :set_project, only: [:index, :new, :create]

  authorize_resource

  def index
    @stories = @project.stories
  end

  def show
    @story = Story.includes(:tasks).find(params[:id])
    @project = @story.project
  end

  def new
    @story = Story.new
  end

  def create
    if @project.stories.create(story_params)
      redirect_to project_stories_url(@project)
    else
      render :new
    end
  end

  private

    def set_project
      @project = Project.find(params[:project_id])
    end

    def story_params
      params.require(:story).
        permit(:importance, :name, :description, :storypoints)
    end
end

app/views/stories/index.html.erb
<div class="row-fluid">
  <div class="span2">
    <%= render 'shared/sidebar' %>
  </div>
  <div class="span10">
    <h1><%= @project.name %></h1>
    <p><%= link_to 'Create New', new_project_story_path(@project), class: 'btn pull-right' %></p>

    <table class='table'>
      <tr>
        <th>Imp.</th>
        <th>Name</th>
        <th>Storypoints</th>
        <th colspan='2'></th>
      </tr>
      <% @stories.each do |story| %>
        <tr>
          <td><%= story.importance %></td>
          <td><%= story.name %></td>
          <td><%= story.storypoints %></td>
          <td><%= link_to 'Show', story_path(@project, @story), class: 'btn' %></td>
          <td><%= link_to 'Edit', '#', class: 'btn' %></td>
        </tr>
      <% end %>
    </table>
 
  </div>
</div>

app/views/stories/new.html.erb
<h1>New story</h1>

<%= form_for([@project, @story], html: { class: 'form-horizontal' }) do |f| %>
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% @story.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :importance, class: 'control-label' %>
    <div class="controls">
      <%= f.number_field :importance %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :name, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, class: 'control-label' %>
    <div class="controls">
      <%= f.text_area :description %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :storypoints, class: 'control-label' %>
    <div class="controls">
      <%= f.number_field :storypoints %>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <%= f.submit "Create", class: 'btn' %>
    </div>
  </div>
<% end %>

app/views/stories/show.html.erb
<div class="row-fluid">
  <div class="span2">
    <%= render 'shared/sidebar' %>
  </div>
  <div class="span10">
    <div class="row-fluid">
      <div class="span12">
        <h2><%= @story.name %></h2>
        <p><%= @story.description %></p>
        <p><%= "#{@story.storypoints} storypoints" %></p>
        <p><%= "#{@story.hours_left} hours left (task-based)" %></p>
      </div>
    </div>
    <div class="row-fluid">
      <div class="span12">
        <h2>Tasks</h2>
        <p><%= link_to 'Add Task', new_story_task_path(@story), class: 'btn' %></p>
        <table class="table table-bordered table-hover">
          <tbody>
            <% @story.tasks.each do |task| %>
              <tr>
                <td><%= link_to task.name, task %></td>
                <td><%= "#{task.original_estimation}h left" %></td>
                <td>
                  <%= link_to 'Edit', edit_task_path(task) %> |
                  <%= link_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' } %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>